---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sre-lab-latency
  name: sre-latency-lab-mock-api
  labels:
    app: sre-latency-lab-mock-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sre-latency-lab-mock-api
  template:
    metadata:
      labels:
        app: sre-latency-lab-mock-api
    spec:
      containers:
        - name: sre-latency-lab-mock-api
          image: hugonico7/sre-latency-lab-mock-api:1.1.3
          ports:
            - containerPort: 8080
          env:
            - name: OTEL_SERVICE_NAME
              value: "sre-mock-api"
            - name: "DEPENDENCY_URL"
              value: "http://sre-latency-lab-mock-dependency-svc:8080"
            - name: "OTEL_ENDPOINT"
              value: "otel-collector.monitoring.svc.cluster.local"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.instance.id=$(POD_NAME)
