---
services:
  watchtower:
    container_name: watchtower
    restart: always
    image: containrrr/watchtower
    networks:
      - services
    environment:
      WATCHTOWER_CLEANUP: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  services:
    external: true
