---
services:
  adguard:
    image: adguard/adguardhome
    restart: unless-stopped
    container_name: Adguard
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "853:853"
    networks:
      services:
        ipv4_address: 172.18.0.10
    volumes:
      - .:/opt/adguardhome/work
      - .:/opt/adguardhome/conf

networks:
  services:
    external: true
    ipam:
      config:
        - subnet: 172.18.0.0/16
