---
apiVersion: v1
kind: Service
metadata:
  namespace: sre-lab-latency
  name: sre-latency-lab-mock-dependency-svc
spec:
  selector:
    app: sre-latency-lab-mock-dependency
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
