services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    networks:
      services:
        ipv4_address: 172.18.0.12
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

networks:
  services:
    external: true
    ipam:
      config:
        - subnet: 172.18.0.0/16

volumes:
  portainer_data:
